New AIR Runtime Release 33.1.1.698
airsdk/airsdk.dev pull request #29
Opened 2021-12-02 14:34 UTC by 2jfw

2021-12-02 21:25 UTC, marchbold requested changes
- You should use markdown syntax for headers i.e. `## Changes and Issues`
- Don't use `</br>`, they aren't needed in markdown and aren't valid html.

2021-12-03 08:45 UTC, 2jfw commented
> * You should use markdown syntax for headers i.e. `## Changes and Issues`
> * Don't use `</br>`, they aren't needed in markdown and aren't valid html.

Alright, thanks! I will keep that in mind 👍

2021-12-15 14:31 UTC, 2jfw commented
Though a bit late, I fixed the issue/pull request: I was using unescaped html tags

2021-12-15 22:42 UTC, marchbold approved these changes

2021-12-15 22:43 UTC, merged